stages:
  preprocess:
    cmd: python raw_dataset/preprocess_dataset.py
    deps:
    - raw_dataset/preprocess_dataset.py
    - raw_dataset/weather.csv
    - raw_dataset/utils_and_constants.py
    outs:
    - processed_dataset/weather.csv
  hp_tune:
    # Set the hyperparameter tuning command
    cmd: python raw_dataset/hp_tuning.py
    deps:
    - processed_dataset/weather.csv
    # Specify the hyperparameter configuration as dependency
    - raw_dataset/hp_config.json
    # Specify the hyperparameter script as dependency
    - raw_dataset/hp_tuning.py
    - raw_dataset/utils_and_constants.py
    outs:
      - hp_tuning_results.md:
          cache: false
  train:
    cmd: python raw_dataset/train.py
    deps:
    - raw_dataset/model.py
    - raw_dataset/metrics_and_plots.py
    - processed_dataset/weather.csv
    - raw_dataset/train.py
    - raw_dataset/utils_and_constants.py
    - raw_dataset/rfc_best_params.json
    outs:
    - confusion_matrix.png
    metrics:
    # Specify the metrics file as target
    - metrics.json:
        cache: false
    plots:
    # Set the target to the file containing predictions data
    - predictions.csv:
        # Write the plot template
        template: confusion_normalized
        x: predicted_label
        y: true_label
        x_label: 'Predicted label'
        y_label: 'True label'
        title: Confusion matrix
        # Set the cache parameter to store
        # plot data in git repository
        cache: false
